name: Deploy Static Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'aws-static-site/site/**'
      - '.github/workflows/deploy-site.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Upload Site to S3
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync site files to S3
        run: |
          aws s3 sync aws-static-site/site/ s3://bbhelpingedge.org --delete
